# Generated by Django 3.2.16 on 2022-11-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=12)),
                ('user', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
